// LOCALHOST 
### GET all contacts 
GET http://localhost:8080/contacts 

### GET contact by id
GET http://localhost:8080/contacts/66355ace71d7707be63a69ca 

### Create contact 
POST http://localhost:8080/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Pamela", 
    "lastName":"Gutierrez", 
    "email":"pamelag@test.com", 
    "favoriteColor":"Pink", 
    "birthday":"09/11/2001"
}

### Update Contact
PUT http://localhost:8080/contacts/66355ace71d7707be63a69ca HTTP/1.1 
content-type: application/json

{
    "firstName":"Isaac", 
    "lastName":"Gutierrez", 
    "email":"igutierrez@gmail.com", 
    "favoriteColor":"Green", 
    "birthday":"04/15/1996"
}

### Delete Contact
DELETE http://localhost:8080/contacts/663c48f78dec82f3fe8a2cbc HTTP/1.1






// PRODUCTION Deploy 
### GET all contacts 
GET https://cse341-node-sndv.onrender.com/contacts

### GET contact by id
GET https://cse341-node-sndv.onrender.com/contacts/66355ace71d7707be63a69ca 

### Create contact 
POST https://cse341-node-sndv.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Pamela", 
    "lastName":"Gutierrez", 
    "email":"pamelag@test.com", 
    "favoriteColor":"Pink", 
    "birthday":"09/11/2001"
}

### Update Contact
PUT https://cse341-node-sndv.onrender.com/contacts/66355b0a71d7707be63a69cc HTTP/1.1 
content-type: application/json

{
    "firstName":"Isaac", 
    "lastName":"Gutierrez", 
    "email":"test@gmail.com", 
    "favoriteColor":"Green", 
    "birthday":"20/15/1996"
}

### Delete Contact
DELETE https://cse341-node-sndv.onrender.com/contacts/66355b0a71d7707be63a69cc HTTP/1.1